"""
Eventyay Python SDK

A modern, type-safe Python client library for the Eventyay API.
Supports both synchronous and asynchronous usage with Pydantic models.
"""

__version__ = "0.1.0"
__author__ = "Shivam Pawar"
__email__ = "shivam.pawar.7217@example.com"

from .async_client import AsyncEventyayClient
from .client import EventyayClient
from .exceptions import (
    EventyayAPIError,
    EventyayAuthenticationError,
    EventyayConnectionError,
    EventyayNotFoundError,
    EventyayParsingError,
    EventyayRateLimitError,
    EventyayTimeoutError,
    EventyayValidationError,
)
from .models import (
    AccessCode,
    AccessCodeList,
    Attendee,
    AttendeeList,
    DiscountCode,
    DiscountCodeList,
    Event,
    EventList,
    EventSubTopic,
    EventSubTopicList,
    EventTopic,
    EventTopicList,
    EventType,
    EventTypeList,
    Feedback,
    FeedbackList,
    GenericResource,
    GenericResourceList,
    Microlocation,
    MicrolocationList,
    Notification,
    NotificationList,
    Order,
    OrderList,
    Organizer,
    OrganizerList,
    Page,
    PageList,
    Role,
    RoleInvite,
    RoleInviteList,
    RoleList,
    Session,
    SessionList,
    Service,
    ServiceList,
    Setting,
    SettingList,
    Speaker,
    SpeakerList,
    Sponsor,
    SponsorList,
    Tax,
    TaxList,
    Ticket,
    TicketTag,
    TicketTagList,
    TicketList,
    Track,
    TrackList,
    User,
    UserList,
)

__all__ = [
    # Clients
    "EventyayClient",
    "AsyncEventyayClient",
    # Exceptions
    "EventyayAPIError",
    "EventyayAuthenticationError",
    "EventyayNotFoundError",
    "EventyayValidationError",
    "EventyayConnectionError",
    "EventyayTimeoutError",
    "EventyayRateLimitError",
    "EventyayParsingError",
    # Models
    "AccessCode",
    "AccessCodeList",
    "Organizer",
    "OrganizerList",
    "Event",
    "EventList",
    "EventType",
    "EventTypeList",
    "EventTopic",
    "EventTopicList",
    "EventSubTopic",
    "EventSubTopicList",
    "Attendee",
    "AttendeeList",
    "Speaker",
    "SpeakerList",
    "Session",
    "SessionList",
    "Track",
    "TrackList",
    "Microlocation",
    "MicrolocationList",
    "Notification",
    "NotificationList",
    "Ticket",
    "TicketList",
    "Sponsor",
    "SponsorList",
    "DiscountCode",
    "DiscountCodeList",
    "Order",
    "OrderList",
    "Page",
    "PageList",
    "Tax",
    "TaxList",
    "Service",
    "ServiceList",
    "User",
    "UserList",
    "Role",
    "RoleList",
    "RoleInvite",
    "RoleInviteList",
    "Feedback",
    "FeedbackList",
    "GenericResource",
    "GenericResourceList",
    "Setting",
    "SettingList",
    "TicketTag",
    "TicketTagList",
]
